/* eslint-disable */
module.exports = [
    {
        "barrier_category": "asian",
        "barriers": 0,
        "contract_category": "asian",
        "contract_category_display": "Asians",
        "contract_display": "asian up",
        "contract_type": "ASIANU",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "asian",
        "barriers": 0,
        "contract_category": "asian",
        "contract_category_display": "Asians",
        "contract_display": "asian down",
        "contract_type": "ASIAND",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "639.4049",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "639.4049",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "forward_starting_options": [
            {
                "close": 1470355199,
                "date": 1470268800,
                "open": 1470268800
            },
            {
                "close": 1470441599,
                "date": 1470355200,
                "open": 1470355200
            },
            {
                "close": 1470527999,
                "date": 1470441600,
                "open": 1470441600
            }
        ],
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "up",
        "start_type": "forward",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "forward_starting_options": [
            {
                "close": 1470355199,
                "date": 1470268800,
                "open": 1470268800
            },
            {
                "close": 1470441599,
                "date": 1470355200,
                "open": 1470355200
            },
            {
                "close": 1470527999,
                "date": 1470441600,
                "open": 1470441600
            }
        ],
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "down",
        "start_type": "forward",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "+0.1815",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "+0.1815",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "+0.1048",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "+0.1048",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "matches",
        "contract_type": "DIGITMATCH",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
        ],
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "match",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "differs",
        "contract_type": "DIGITDIFF",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
        ],
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "differ",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "non_financial",
        "barriers": 0,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "odd",
        "contract_type": "DIGITODD",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "odd",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "non_financial",
        "barriers": 0,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "even",
        "contract_type": "DIGITEVEN",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "even",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "over",
        "contract_type": "DIGITOVER",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8
        ],
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "over",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "under",
        "contract_type": "DIGITUNDER",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9
        ],
        "market": "volidx",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "under",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends In/Out",
        "contract_display": "ends outside",
        "contract_type": "EXPIRYMISS",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "639.4049",
        "low_barrier": "611.8489",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends In/Out",
        "contract_display": "ends between",
        "contract_type": "EXPIRYRANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "639.4049",
        "low_barrier": "611.8489",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends In/Out",
        "contract_display": "ends outside",
        "contract_type": "EXPIRYMISS",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+0.5138",
        "low_barrier": -0.5127,
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends In/Out",
        "contract_display": "ends between",
        "contract_type": "EXPIRYRANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+0.5138",
        "low_barrier": -0.5127,
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "amount_per_point": 1,
        "barrier_category": "spreads",
        "barriers": 0,
        "contract_category": "spreads",
        "contract_category_display": "Spreads",
        "contract_display": "spread up",
        "contract_type": "SPREADU",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "10",
        "min_contract_duration": "5",
        "sentiment": "up",
        "start_type": "spot",
        "stop_loss": 0.12,
        "stop_profit": 10,
        "stop_type": "point",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "amount_per_point": 1,
        "barrier_category": "spreads",
        "barriers": 0,
        "contract_category": "spreads",
        "contract_category_display": "Spreads",
        "contract_display": "spread down",
        "contract_type": "SPREADD",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "10",
        "min_contract_duration": "5",
        "sentiment": "down",
        "start_type": "spot",
        "stop_loss": 0.12,
        "stop_profit": 10,
        "stop_type": "point",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays In/Goes Out",
        "contract_display": "stays between",
        "contract_type": "RANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "639.4049",
        "low_barrier": "611.8489",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays In/Goes Out",
        "contract_display": "goes outside",
        "contract_type": "UPORDOWN",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "639.4049",
        "low_barrier": "611.8489",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays In/Goes Out",
        "contract_display": "stays between",
        "contract_type": "RANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+0.5138",
        "low_barrier": -0.5127,
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays In/Goes Out",
        "contract_display": "goes outside",
        "contract_type": "UPORDOWN",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+0.5138",
        "low_barrier": -0.5127,
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "639.4049",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "touches",
        "contract_type": "ONETOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "639.4049",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "does not touch",
        "contract_type": "NOTOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "volidx",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "+0.5138",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "touches",
        "contract_type": "ONETOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    },
    {
        "barrier": "+0.5138",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "does not touch",
        "contract_type": "NOTOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "volidx",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
    }
];
